### ISSUE TITLE
SharePoint JSLink file create/update operations do not work properly when not root site collection

### ISSUE THREAD

**Issue by vgrem** [andrei-markeev/cisar#1]
Hey,

Like the title says, the error occurs while trying to create/update  JSLink file when site collection uses managed path.
Potentially the issue is related with the method SP.Web.getFolderByServerRelativeUrl, it seems path variable does not take into account site relative url in SPActions.getCode_createFileInSharePoint method since it's value comes from FilesList.filespath property as '/Style Library/': 

var files = context.get_site().get_rootWeb().getFolderByServerRelativeUrl(path).get_files();

After applying the following fix:
var files = context.get_site().get_rootWeb().getFolderByServerRelativeUrl(_spPageContextInfo.siteServerRelativeUrl + path).get_files();

the file could be saved/updated properly.

Best regards,
Vadim the Great!

**Comment by andrei-markeev** [comment]
Should work now
