### ISSUE TITLE
Allow a JS-Link to: ~/site/...

### ISSUE THREAD

**Issue by masterl1983** [andrei-markeev/cisar#13]
Hi, I do have a question related to CISAR. Within the extension there is the possibility to change the path. I am trying to set the path so the JS-Link property would be set to something like: ~site/SiteAssets/

Is that possible?﻿

**Comment by andrei-markeev** [comment]
Not at the moment. I will implement it, as you're already at least second person asking for this feature, but hard to promise any certain date of completion.

**Comment by Danny-Engelman** [comment]
When changing that code see if you can spot where it creates double references in the JSlink; I can't reproduce it but every now and then I have to open the WebPartProperties and fix 
    "~site collection/style library/myfile.js|~site collection/style library/myfile.js"

Maybe before your write the JSlink split on | and remove the doubles is an easy fix

**Comment by masterl1983** [comment]
Hi. When using ~site option I do get errors that the file can not be saved.
