### ISSUE TITLE
No CSR enabled WebParts found on this page

### ISSUE THREAD

**Issue by Danny-Engelman** [andrei-markeev/cisar#20]
I haven't used Cisar for a week or 3

Now get:

![](http://i.imgur.com/yhBRbpf.jpg)

Since its Cisar 1.3 from february, I presume something changed on Office365

**Comment by andrei-markeev** [comment]
I have one guess, they've got a new "design" for document libraries that doesn't use CSR at all. It should be possible to disable this feature. Could it be you're hitting this problem? Do the customizations still work and only Cisar shows "No CSR-enabled webparts" or CSR doesn't work at all?

**Comment by Danny-Engelman** [comment]
No, I have done a lot with the "new" View, thats not it
all JSLinks (and thus CSR) execute fine.
Its Cisar not recognizing the webparts on List/Library View pages
It does pick up the webparts on other ASPX pages (start.aspx)

I have tested 2 PCs, 3 Tenants and different Chrome profiles

I presume its in SPActions.ts
where you $get the webparts

Can I get/trace into Cisar inner objects with the console somehow?
I copy/pasted the $get code in the console and they work fine.

Closing F12 and reopening Cisar doesn't help, so its not a problem that the DOM isn't available yet.

Maybe you could add console.log out if a global `g_tracecisar` exists

**Comment by SuleymanA** [comment]
Love Cisar and working with it. So a big thank you!!!!

I am also experiencing the same problem (O365). It does show the existing jslink files.

**Comment by SuleymanA** [comment]
Could it be that you are by default looking for the webpartzone "MSOZoneCell_WebPartWPQ2"? My form appears to be in "MSOZoneCell_WebPartWPQ1" now. In this section of SPAction.ts:

`           var webparts = [];
            var wp_properties = [];
            var wpqId = 2;

```
        if (GetUrlKeyValue("PageView") == "Personal") {
            window["g_Cisar_JSLinkUrls"] = "personal";
            return { webparts: [], displayTemplates: []};
        }

        while ($get("MSOZoneCell_WebPartWPQ" + wpqId) != null) {`
```

Not sure if I am missing anything but looks like wpqId is static so only looking in "MSOZoneCell_WebPartWPQ2".

**Comment by SuleymanA** [comment]
Downloaded and tested extention with wpqId 1 and at now gives me the option to add a jslink file to the form webpart. I need to fully test it but appears to be working.

**Comment by andrei-markeev** [comment]
Hi,

@SuleymanA thanks for your feedback, investigation and the proposed solution!

I think it is totally OK to use wpq=1. I used 2 because first webpart on page appears to be the searchbox, so usually real webparts on the page would start with WPQ2. So yep, something has changed in O365 masterpage. I will change the Cisar code appropriately!

**Comment by Danny-Engelman** [comment]
FYI The Chrome Store still has version 1.3 (without the bug fix)

**Comment by andrei-markeev** [comment]
Yep I know, I'm doing some final polishing of the 2.0 version, it will be out very soon!... :)

**Comment by Danny-Engelman** [comment]
[excited] Feels like upcoming Christmas :-)
