### ISSUE TITLE
Cisar does not show in Developer Tools

### ISSUE THREAD

**Issue by Danny-Engelman** [andrei-markeev/cisar#4]
I tried both the Store install and the manual install, but Cisar does not show in the Developer Tools.

Trying to install again from the Store gives me the error: This item is already being downloaded and added into Chrome.
Corresponding error in console:
![](http://i.imgur.com/oJfNiX2.jpg)

I can select Reload, but nothing really happens

There is no Cisar in: chrome://extensions/

if you need any more info let me know

TNX!

**Comment by andrei-markeev** [comment]
Hi,

It seems to be a Chrome issue unrelated to the extension itself.

I googled a bit and there's an accepted answer here on superuser:

http://superuser.com/questions/836029/installed-extension-doesnt-show-up

Could you try following the steps provided there?

**Comment by Danny-Engelman** [comment]
I have 41 items in the extension folder.. I presume they are required, so
am not deleting them untill I know nothing will be lost.
Looks to me Chrome Profiles each have their own folder... I have 10
profiles.. so have to search.



Danny Engelman <http://www.engelman.nl/>
danny@engelman.nl
http://www.LinkedIN.com/in/dannyengelman
<http://www.linkedin.com/in/dannyengelman>

► 365CSI.nl <http://www.CSI365.nl> - Office 365 Blended Learning (preview
only, opens august 2015)
bikeswap.org <http://www.bikeswap.org> - borrow a motorcycle, loan a
motorcyle


2015-07-19 18:25 GMT+02:00 Andrei Markeev <notifications@github.com>:

**Comment by Danny-Engelman** [comment]
can't install other extensions as well... i'll continue the adventure


Danny Engelman <http://www.engelman.nl/>
danny@engelman.nl
http://www.LinkedIN.com/in/dannyengelman
<http://www.linkedin.com/in/dannyengelman>

► 365CSI.nl <http://www.CSI365.nl> - Office 365 Blended Learning (preview
only, opens august 2015)
bikeswap.org <http://www.bikeswap.org> - borrow a motorcycle, loan a
motorcyle


2015-07-19 18:33 GMT+02:00 Danny Engelman <danny@engelman.nl>:

**Comment by Danny-Engelman** [comment]
Installed it on my laptop under the same Chrome acount, now its available on my DEV machine as well
