### ISSUE TITLE
JSlink remains on WebPart when the CSR file is deleted manually from the Style Library

### ISSUE THREAD

**Issue by Danny-Engelman** [andrei-markeev/cisar#7]
I had to delete the file manually from the Style Library because the code ran into an endless loop.
When I reopened Cisar on the View page it looked up the file (from JSlink in the WebPart) which returns 404 code in the Cisar editor
Now the editor doesn't save any new code added in the Cisar editor
Only way to resolve is to manually delete the JSlink from the webpart (or recreate the file in the Style Library)

Suggested feature: When Cisar detects a 404, ask the user if the JSlink should be removed OR the file should be recreated.

**Comment by Danny-Engelman** [comment]
Note: at one point during testing I couldn't even open the View page anymore to delete the JSlink ; the Browser stalled.

I deleted the the JSlink from the aspx file using SharePoint Designer.

**Comment by Danny-Engelman** [comment]
Just for documentation:

**Before recreating Cisar files and JSlinks again**
- recover deleted files (in the Style Library) from the SiteCollection Recycle Bin 
- Edit the file with SharePoint Designer so your code doesn't cause any trouble
- Open Cisar and Create a file with the Same filename.. it will Load your existing CSR file

**Comment by andrei-markeev** [comment]
Good idea as always, thanks!
I'm a bit tight on time right now but I'll definitely consider this feature as next in implementation queue.

**Comment by Danny-Engelman** [comment]
No worries, I can work around all issues, reporting them mainly for others.
