### ISSUE TITLE
Reference to (original) URL where the CSR file was used in a (first) JSlink connection

### ISSUE THREAD

**Issue by Danny-Engelman** [andrei-markeev/cisar#8]
While testing I have created multiple CSR files (in the default /Style Library/) on multiple sites.
I now do not know in which sites I used which CSRfiles.

Suggested feature: When the Cisar file is created add a comment section displaying the URL(s) where the file was JSlinked
eg:
/*
 Created on: <date>
JSLinks:
  https://365csi.sharepoint.com/sites/VM/Lists/Tasks/AllItems.aspx
  https://365csi.sharepoint.com/sites/Demo/Lists/Tasks/MyItems.aspx
/JSLinks
*/

**Comment by andrei-markeev** [comment]
What you suggest will track only cases when a file was JSLink'ed via Cisar, which can be really confusing if there're some other guys in the team who don't use Cisar...

**Comment by Danny-Engelman** [comment]
If Cisar sees a WebPart is allready linked it:

A. Would be nice to notify the developer
B. Could be added to the (comments) list

It should be easy with Cisar to delete any existing links; the Microsoft way is way too much clicks.
Again, not for me.. I have a Bookmarklet which resets JSlink values. (but with Cisar it could be easier done)

**Comment by Danny-Engelman** [comment]
Lets not waist time on not-really-urgent issues.... closing this

**Comment by Danny-Engelman** [comment]
Lets focus on important issues.. closing this
