### ISSUE TITLE
Personal Views not recognized

### ISSUE THREAD

**Issue by Danny-Engelman** [andrei-markeev/cisar#9]
When creating a new PERSONAL View based on an existing View (with CSR) 
Cisar errors:

> Error when retrieving properties for the CSR webparts on the page: Specified argument was out of the range of valid values.

**Comment by andrei-markeev** [comment]
Nice catch, thanks! I'll look into that.

**Comment by Danny-Engelman** [comment]
I can not find a way to set a JSlink.

The misconception is we all call it a View Templates while technically we
attach a JSlink to a WebPart.. which displays a View.

I fear Personal Views are all 2003 technology.. they do not get their own
ASPX page (or own ListView WebPart)
Personal Views are served like:
/Lists/Tasks/PersonalViews.aspx?PageView=Personal&ShowWebPart={A8E42828-D606-4089-83CB-D8AFC5041B31}

And when you EDIT that page... Its is Blank!

Even the good old &toolpaneview=2 hack doesn't reveal any webparts

Tried one other ViewID from the same list for the ShowWebPart URL
parameter, but it presents a totally blank page

I use JSOM code to set JSlinks on WebParts with one click.. it doesn't work
for this PersonalViews.aspx page.

Couldn't find any blogs related to this.

I am inclined to say that you can NOT apply CSR to Personal Views,

seems to me the View declaration (but not the WebPart with a JSlink option)
is stored in the database

That means... Issue closed :-)

**Comment by andrei-markeev** [comment]
Oh, don't give up just yet! :)

The thing is, usual way to operate webparts is to retrieve LimitedWebPartManager with PersonalizationScope=Shared, which is exactly what I do in Cisar: https://github.com/andrei-markeev/cisar/blob/master/Code/SPActions.ts#L16

I think if I would use PersonalizationScope=Personal, this will solve the issue. The point is however, that editing personalized view obviously will only affect this particular view of this particular user. Which I guess is not what you want.

I am thinking now of what is the best way to handle this situation in Cisar.

Btw also when you try editing the personalized page and you see that this page is blank - I also tried that and got same results, - you might notice that in the URL it has parameter `PageView=Shared`...

I think it if a user doesn't have enough right to edit Shared view, he will actually edit Personal view. Not sure.

**Comment by andrei-markeev** [comment]
Hi, if you're interested in practical solution, I [answered](http://sharepoint.stackexchange.com/a/164479/1430) the question you posted on SPSE. The explained solution actually works, at least on my environment.

So yes, CSR **can** be applied to personal views.

Considering Cisar:
1. I'll try to fix the `Specified argument was out of the range of valid values.` error ASAP, it seems to appear on some other pages as well, not only on personal views.
2. Next, I think the sound behavior for Cisar on personal view pages would be to not show anything in the left pane, signifying that there's nothing that can be edited here.
3. I will check PageView=Personal in query string and display appropriate notification, telling users that this page is personal and generally it doesn't make sense to edit it, and if they want to edit personal pages, they should apply the CSR script on a more global scope.

**Comment by andrei-markeev** [comment]
Done :)

![image](https://cloud.githubusercontent.com/assets/5181724/11854095/4bdea780-a44a-11e5-9088-a630a6e7c899.png)
